### ISSUE TITLE
Will this be released soon

### ISSUE THREAD

**Issue by asundrus** [totorewa/totos-carpet-tweaks#2]
This is not an issue, but did not know where to aski this, as I really would love the feature of Discount hsaring.

**Comment by 1schlick** [comment]
I was able to download and compile the mod myself. See this video for instructions... https://www.youtube.com/watch?v=aFr5Vg6xupg

**Comment by DragonEggBedrockBreaking** [comment]
You can also just use GitHub Actions

**Comment by totorewa** [comment]
Sorry it's taken me a while to respond. I wasn't expecting this mod to get attention or be found and so wasn't monitoring the repository.  
   
I've made a build of the current main branch and have published it as a release.  
You can find it at [https://github.com/totorewa/totos-carpet-tweaks/releases/tag/v0.1.3-beta](https://github.com/totorewa/totos-carpet-tweaks/releases/tag/v0.1.3-beta)

**Comment by DragonEggBedrockBreaking** [comment]
> I wasn't expecting this mod to get attention or be found

I added it to the official list of carpet extensions a while back :-)
https://github.com/gnembon/fabric-carpet/wiki/List-of-Carpet-extensions
