### ISSUE TITLE
1.18.1 release?

### ISSUE THREAD

**Issue by Decrepitdoors** [totorewa/totos-carpet-tweaks#8]
I see the build says it's updated to 1.18 but there is no release, downloading and trying to build wouldn't work, uploaded to gradle scan, incase that's helpful https://scans.gradle.com/s/oorkbs57kkdbo

**Comment by totorewa** [comment]
Release for 1.18.x can be found here: https://github.com/totorewa/totos-carpet-tweaks/releases/tag/0.2.4
